### ISSUE TITLE
Complete Teardown of tibanna

### ISSUE THREAD

**Issue by bayolau** [4dn-dcic/tibanna#272]
Thank you for developing this tool. I've been successfully using Tibanna.

I've followed tibanna documentation, but I'm not sure how to do a complete tear down after `tibanna deploy_unicorn`. I do see a step function being provisioned, are there any other resources? How about temporary files and logs?

Is there a simple command to remove everything?

**Comment by SooLee** [comment]
@bayolau Thank you for using Tibanna. Now we have a cleanup function (`0.16.0`): [release note](https://github.com/4dn-dcic/tibanna/releases/tag/v0.16.0)

**Comment by bayolau** [comment]
It seems to work, thanks! I notice that there's a `tibanna_lambda_init_role` and a dynamo table remaining. This brought up a question. Is it safe for individual users (of the sam aws account) to create/delete their own Tibanna Unicorn?

**Comment by SooLee** [comment]
@bayolau `tibanna_lambda_init_role` and the dynamo table are shared across all tibanna unicorns, so I didn't add that to the cleanup, so that deleting one unicorn wouldn't affect another one. In general, I think it's safe to cleanup for each tibanna unicorn without worrying about affecting other unicorns, except when using a suffix (-s option for deployment) - a user group with different suffices share the same IAM permissions, so if you want to delete only one unicorn with a suffix, that it would be safer not to delete the IAM permissions (use -G option of cleanup)

**Comment by bayolau** [comment]
thanks!
